spring.application.name=CourseRegSystem

# Database Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/advanced_course_reg?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mac@1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Database Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Spring Security Config
# Allow frame option headers for H2 console or simple layouts if needed (optional)
spring.headers.frame-options.disable=true

# Server configuration
server.port=8081
